from __future__ import annotations


WOWHEAD_CATEGORY_URLS = {
    "herbalism": "https://www.wowhead.com/items/trade-goods/herbs",
    "mining": "https://www.wowhead.com/items/trade-goods/metal-and-stone",
    "skinning": "https://www.wowhead.com/items/trade-goods/leather",
}


GATHERABLE_SEEDS = {
    "herbalism": {
        "Classic": [
            "Peacebloom",
            "Silverleaf",
            "Earthroot",
            "Mageroyal",
            "Briarthorn",
            "Bruiseweed",
            "Wild Steelbloom",
            "Kingsblood",
            "Liferoot",
            "Fadeleaf",
            "Goldthorn",
            "Khadgar's Whisker",
            "Wintersbite",
            "Firebloom",
            "Purple Lotus",
            "Arthas' Tears",
            "Sungrass",
            "Blindweed",
            "Ghost Mushroom",
            "Gromsblood",
            "Golden Sansam",
            "Dreamfoil",
            "Mountain Silversage",
            "Plaguebloom",
            "Icecap",
            "Black Lotus",
        ],
        "The Burning Crusade": [
            "Felweed",
            "Dreaming Glory",
            "Ragveil",
            "Flame Cap",
            "Terocone",
            "Ancient Lichen",
            "Mana Thistle",
            "Nightmare Vine",
            "Netherbloom",
            "Fel Lotus",
        ],
        "Wrath of the Lich King": [
            "Goldclover",
            "Tiger Lily",
            "Talandra's Rose",
            "Lichbloom",
            "Icethorn",
            "Adder's Tongue",
            "Fire Leaf",
            "Deadnettle",
        ],
        "Cataclysm": [
            "Cinderbloom",
            "Stormvine",
            "Azshara's Veil",
            "Heartblossom",
            "Twilight Jasmine",
            "Whiptail",
        ],
        "Mists of Pandaria": [
            "Green Tea Leaf",
            "Silkweed",
            "Rain Poppy",
            "Snow Lily",
            "Fool's Cap",
            "Golden Lotus",
        ],
        "Warlords of Draenor": [
            "Frostweed",
            "Gorgrond Flytrap",
            "Starflower",
            "Nagrand Arrowbloom",
            "Talador Orchid",
            "Fireweed",
        ],
        "Legion": [
            "Aethril",
            "Dreamleaf",
            "Fjarnskaggl",
            "Foxflower",
            "Starlight Rose",
            "Felwort",
        ],
        "Battle for Azeroth": [
            "Riverbud",
            "Sea Stalk",
            "Siren's Pollen",
            "Anchor Weed",
            "Winter's Kiss",
            "Akunda's Bite",
            "Star Moss",
            "Zin'anthid",
        ],
        "Shadowlands": [
            "Death Blossom",
            "Rising Glory",
            "Marrowroot",
            "Vigil's Torch",
            "Widowbloom",
            "Nightshade",
            "First Flower",
        ],
        "Dragonflight": [
            "Hochenblume",
            "Saxifrage",
            "Bubble Poppy",
            "Writhebark",
            "Zaralek Glowspores",
        ],
        "The War Within": [
            "Mycobloom",
            "Luredrop",
            "Orbinid",
            "Blessing Blossom",
            "Arathor's Spear",
            "Null Lotus",
        ],
        "Midnight": [
            "Tranquility Bloom",
            "Argentleaf",
            "Azeroot",
            "Mana Lily",
            "Sanguithorn",
            "Nocturnal Lotus",
        ],
    },
    "mining": {
        "Classic": [
            "Copper Ore",
            "Tin Ore",
            "Silver Ore",
            "Iron Ore",
            "Gold Ore",
            "Mithril Ore",
            "Truesilver Ore",
            "Thorium Ore",
            "Dark Iron Ore",
        ],
        "The Burning Crusade": [
            "Fel Iron Ore",
            "Adamantite Ore",
            "Eternium Ore",
            "Khorium Ore",
            "Nethercite Ore",
        ],
        "Wrath of the Lich King": [
            "Cobalt Ore",
            "Saronite Ore",
            "Titanium Ore",
        ],
        "Cataclysm": [
            "Obsidium Ore",
            "Elementium Ore",
            "Pyrite Ore",
        ],
        "Mists of Pandaria": [
            "Ghost Iron Ore",
            "Kyparite",
            "White Trillium Ore",
            "Black Trillium Ore",
        ],
        "Warlords of Draenor": [
            "Blackrock Ore",
            "True Iron Ore",
        ],
        "Legion": [
            "Leystone Ore",
            "Felslate",
            "Empyrium",
        ],
        "Battle for Azeroth": [
            "Monelite Ore",
            "Storm Silver Ore",
            "Platinum Ore",
            "Osmenite Ore",
        ],
        "Shadowlands": [
            "Laestrite Ore",
            "Solenium Ore",
            "Oxxein Ore",
            "Phaedrum Ore",
            "Sinvyr Ore",
            "Elethium Ore",
            "Progenium Ore",
        ],
        "Dragonflight": [
            "Serevite Ore",
            "Draconium Ore",
            "Khaz'gorite Ore",
        ],
        "The War Within": [
            "Bismuth",
            "Aqirite",
            "Ironclaw Ore",
            "Null Stone",
        ],
        "Midnight": [
            "Refulgent Copper Ore",
            "Umbral Tin Ore",
            "Brilliant Silver Ore",
            "Dazzling Thorium",
        ],
    },
    "skinning": {
        "Classic": [
            "Ruined Leather Scraps",
            "Light Leather",
            "Light Hide",
            "Medium Leather",
            "Medium Hide",
            "Heavy Leather",
            "Heavy Hide",
            "Thick Leather",
            "Thick Hide",
            "Rugged Leather",
            "Rugged Hide",
            "Raptor Hide",
            "Thin Kodo Leather",
            "Slimy Murloc Scale",
            "Thick Murloc Scale",
            "Deviate Scale",
            "Perfect Deviate Scale",
            "Black Whelp Scale",
            "Green Whelp Scale",
            "Scorpid Scale",
            "Worn Dragonscale",
            "Turtle Scale",
            "Heavy Scorpid Scale",
            "Green Dragonscale",
            "Red Dragonscale",
            "Blue Dragonscale",
            "Black Dragonscale",
            "Devilsaur Leather",
            "Warbear Leather",
            "Core Leather",
            "Primal Bat Leather",
            "Primal Tiger Leather",
            "Dreamscale",
        ],
        "The Burning Crusade": [
            "Knothide Leather",
            "Knothide Leather Scraps",
            "Crystal-Infused Leather",
            "Fel Scales",
            "Fel Hide",
            "Thick Clefthoof Leather",
            "Cobra Scales",
            "Wind Scales",
            "Nether Dragonscales",
        ],
        "Wrath of the Lich King": [
            "Borean Leather Scraps",
            "Borean Leather",
            "Icy Dragonscale",
            "Nerubian Chitin",
            "Jormungar Scale",
            "Arctic Fur",
        ],
        "Cataclysm": [
            "Savage Leather",
            "Savage Leather Scraps",
            "Blackened Dragonscale",
            "Pristine Hide",
            "Scarred Shell Fragment",
            "Deepsea Scale",
        ],
        "Mists of Pandaria": [
            "Mist-Touched Leather",
            "Sha-Touched Leather",
            "Magnificent Hide",
            "Prismatic Scale",
        ],
        "Warlords of Draenor": [
            "Raw Beast Hide",
            "Raw Beast Hide Scraps",
        ],
        "Legion": [
            "Stonehide Leather",
            "Stormscale",
            "Felhide",
            "Wisp-Touched Elderhide",
            "Prime Wardenscale",
            "Fiendish Leather",
        ],
        "Battle for Azeroth": [
            "Coarse Leather",
            "Tempest Hide",
            "Shimmerscale",
            "Mistscale",
            "Blood-Stained Bone",
            "Calcified Bone",
            "Dredged Leather",
            "Cragscale",
        ],
        "Shadowlands": [
            "Desolate Leather",
            "Pallid Bone",
            "Desolate Leather Scraps",
            "Callous Hide",
            "Callous Hide Scraps",
            "Heavy Desolate Leather",
            "Heavy Callous Hide",
            "Gaunt Sinew",
            "Protogenic Pelt",
            "Unseelie Leather",
            "Sinful Leather",
            "Necrotic Leather",
            "Purified Leather",
        ],
        "Dragonflight": [
            "Resilient Leather",
            "Adamant Scales",
            "Dense Hide",
            "Lustrous Scaled Hide",
            "Stonecrust Hide",
            "Mireslush Hide",
            "Deathchill Hide",
            "Infurious Hide",
            "Drygrate Scales",
            "Earthshine Scales",
            "Frostbite Scales",
            "Infurious Scales",
            "Crystalspine Fur",
            "Salamanther Scales",
            "Cacophonous Thunderscale",
            "Rockfang Leather",
            "Pristine Vorquin Horn",
            "Windsong Plumage",
            "Fire-Infused Hide",
            "Flawless Proto Dragon Scale",
            "Bite-Sized Morsel",
            "Exceptional Morsel",
        ],
        "The War Within": [
            "Pristine Pelt",
            "Auric Fleece",
            "Pristine Core Leather",
            "Stormcharged Leather",
            "Gloom Chitin",
            "Thunderous Hide",
            "Sunless Carapace",
            "Kaheti Swarm Chitin",
            "Honed Bone Shards",
            "Bottled Storm",
            "Burning Cinderbee Setae",
            "Superb Beast Fang",
        ],
        "Midnight": [
            "Carapace-Backed Hide",
            "Crystalfused Hide",
            "Writhing Hide",
            "Sporecoated Hide",
            "Leyfused Hide",
            "Peerless Plumage",
            "Carving Canine",
            "Fantastic Fur",
            "Majestic Claw",
            "Majestic Hide",
            "Majestic Fin",
            "Scalewoven Hide",
            "Infused Scalewoven Hide",
        ],
    },
}
